version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./logs/rabbitmq:/etc/logs/rabbitmq
      - ./logs/rabbitmq:/var/log/rabbitmq

  meeting-server:
    container_name: meeting-server
    build:
      context: ./meeting-server
      args:
        - JAR_FILE=meeting-server-1.0.jar
        - VERSION=1.0
      dockerfile: Dockerfile
      #    image: pengpeng163/meeting-server:1.0
    volumes:
      - ./logs:/etc/logs/meeting-server
    #    ports:
    #      - 8080:8080
    environment:
      JWT_HEADER: Authorization


  meeting-gui:
    container_name: meeting-gui
    build:
      context: ./meeting-gui
    #    volumes:
    ports:
      - 8090:8090
      - 80:80
      - 443:443
    environment:
      DB_TYPE: postgres
  meeting-web:
    container_name: meeting-web
    build:
      context: meeting-web
    #    volumes:
    ports:
      - 8080:8080
    environment:
      DB_TYPE: postgres



# Path: ./elsbiz-office-service/src/main/resources/application.yml