server:
  port: 8080
logback:
  level: info

spring:
  ai:
    openai:
      api-key: sess-QEmiMRUspplcZcGTSAUnSCV0WKPbY98TjudMgRb8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: false
    mode: html