server:
  port: ${PORT:8080}
logback:
  level: info

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23litHvfyRrBkL6qQp
            client-secret: 7c4129a7851258a2d77e3ffb80229e87d8c7dde0
            scope: read:user,user:email
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri: '{baseUrl}/login/oauth2/code/github'
            provider:
              github:
                authorization-uri: https://github.com/login/oauth/authorize
                token-uri: https://github.com/login/oauth/access_token
                user-info-uri: https://api.github.com/user
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: openid,profile,email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: name


#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/meeting?ssl=false&serverZoneId=Asia/Shanghai}
#    username: ${DATASOURCE_USERNAME:postgres}
#    password: ${DATASOURCE_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
  r2dbc:
    url: ${DATASOURCE_URL:r2dbc:postgresql://localhost:5432/meeting?ssl=false&serverZoneId=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 10m
      validation-query: SELECT 1
  devtools:
    restart:
      enabled: true
  ai:
    openai:
      api-key: sess-QEmiMRUspplcZcGTSAUnSCV0WKPbY98TjudMgRb8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: false
    mode: html