// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Account.proto

package com.github.meeting.common.connect.model.proto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.github.meeting.common.connect.model.proto.AccountOperationType}
   */
  public enum AccountOperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SIGNIN = 0;</code>
     */
    SIGNIN(0),
    /**
     * <code>LOGOUT = 1;</code>
     */
    LOGOUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SIGNIN = 0;</code>
     */
    public static final int SIGNIN_VALUE = 0;
    /**
     * <code>LOGOUT = 1;</code>
     */
    public static final int LOGOUT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccountOperationType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AccountOperationType forNumber(int value) {
      switch (value) {
        case 0: return SIGNIN;
        case 1: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccountOperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccountOperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccountOperationType>() {
            public AccountOperationType findValueByNumber(int number) {
              return AccountOperationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.meeting.common.connect.model.proto.Account.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccountOperationType[] VALUES = values();

    public static AccountOperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccountOperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.meeting.common.connect.model.proto.AccountOperationType)
  }

  public interface AccountInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.meeting.common.connect.model.proto.AccountInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    java.lang.String getAccountName();
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    java.lang.String getEMail();
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    com.google.protobuf.ByteString
        getEMailBytes();
  }
  /**
   * Protobuf type {@code com.github.meeting.common.connect.model.proto.AccountInfo}
   */
  public static final class AccountInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.meeting.common.connect.model.proto.AccountInfo)
      AccountInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountInfo.newBuilder() to construct.
    private AccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountInfo() {
      account_ = "";
      accountName_ = "";
      eMail_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.meeting.common.connect.model.proto.Account.internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.meeting.common.connect.model.proto.Account.internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.meeting.common.connect.model.proto.Account.AccountInfo.class, com.github.meeting.common.connect.model.proto.Account.AccountInfo.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object account_ = "";
    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accountName_ = "";
    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    @java.lang.Override
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      }
    }
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eMail_ = "";
    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    @java.lang.Override
    public java.lang.String getEMail() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eMail_ = s;
        return s;
      }
    }
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEMailBytes() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eMail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(account_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountName_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eMail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eMail_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(account_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountName_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eMail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eMail_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.meeting.common.connect.model.proto.Account.AccountInfo)) {
        return super.equals(obj);
      }
      com.github.meeting.common.connect.model.proto.Account.AccountInfo other = (com.github.meeting.common.connect.model.proto.Account.AccountInfo) obj;

      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getAccountName()
          .equals(other.getAccountName())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getEMail()
          .equals(other.getEMail())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAccountName().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEMail().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.meeting.common.connect.model.proto.Account.AccountInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.meeting.common.connect.model.proto.AccountInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.meeting.common.connect.model.proto.AccountInfo)
        com.github.meeting.common.connect.model.proto.Account.AccountInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.meeting.common.connect.model.proto.Account.internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.meeting.common.connect.model.proto.Account.internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.meeting.common.connect.model.proto.Account.AccountInfo.class, com.github.meeting.common.connect.model.proto.Account.AccountInfo.Builder.class);
      }

      // Construct using com.github.meeting.common.connect.model.proto.Account.AccountInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        account_ = "";
        accountName_ = "";
        userId_ = 0L;
        eMail_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.meeting.common.connect.model.proto.Account.internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor;
      }

      @java.lang.Override
      public com.github.meeting.common.connect.model.proto.Account.AccountInfo getDefaultInstanceForType() {
        return com.github.meeting.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.meeting.common.connect.model.proto.Account.AccountInfo build() {
        com.github.meeting.common.connect.model.proto.Account.AccountInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.meeting.common.connect.model.proto.Account.AccountInfo buildPartial() {
        com.github.meeting.common.connect.model.proto.Account.AccountInfo result = new com.github.meeting.common.connect.model.proto.Account.AccountInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.meeting.common.connect.model.proto.Account.AccountInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.account_ = account_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.accountName_ = accountName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.eMail_ = eMail_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.meeting.common.connect.model.proto.Account.AccountInfo) {
          return mergeFrom((com.github.meeting.common.connect.model.proto.Account.AccountInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.meeting.common.connect.model.proto.Account.AccountInfo other) {
        if (other == com.github.meeting.common.connect.model.proto.Account.AccountInfo.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getAccountName().isEmpty()) {
          accountName_ = other.accountName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getEMail().isEmpty()) {
          eMail_ = other.eMail_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                account_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                accountName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                eMail_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 1;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        account_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        account_ = getDefaultInstance().getAccount();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        account_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object accountName_ = "";
      /**
       * <code>string accountName = 2;</code>
       * @return The accountName.
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accountName = 2;</code>
       * @return The bytes for accountName.
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accountName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        accountName_ = getDefaultInstance().getAccountName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        accountName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object eMail_ = "";
      /**
       * <code>string eMail = 4;</code>
       * @return The eMail.
       */
      public java.lang.String getEMail() {
        java.lang.Object ref = eMail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eMail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eMail = 4;</code>
       * @return The bytes for eMail.
       */
      public com.google.protobuf.ByteString
          getEMailBytes() {
        java.lang.Object ref = eMail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eMail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eMail_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEMail() {
        eMail_ = getDefaultInstance().getEMail();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The bytes for eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eMail_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.meeting.common.connect.model.proto.AccountInfo)
    }

    // @@protoc_insertion_point(class_scope:com.github.meeting.common.connect.model.proto.AccountInfo)
    private static final com.github.meeting.common.connect.model.proto.Account.AccountInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.meeting.common.connect.model.proto.Account.AccountInfo();
    }

    public static com.github.meeting.common.connect.model.proto.Account.AccountInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountInfo>
        PARSER = new com.google.protobuf.AbstractParser<AccountInfo>() {
      @java.lang.Override
      public AccountInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccountInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.meeting.common.connect.model.proto.Account.AccountInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAccount.proto\022-com.github.meeting.comm" +
      "on.connect.model.proto\"R\n\013AccountInfo\022\017\n" +
      "\007account\030\001 \001(\t\022\023\n\013accountName\030\002 \001(\t\022\016\n\006u" +
      "serId\030\003 \001(\003\022\r\n\005eMail\030\004 \001(\t*.\n\024AccountOpe" +
      "rationType\022\n\n\006SIGNIN\020\000\022\n\n\006LOGOUT\020\001B8\n-co" +
      "m.github.meeting.common.connect.model.pr" +
      "otoB\007Accountb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_meeting_common_connect_model_proto_AccountInfo_descriptor,
        new java.lang.String[] { "Account", "AccountName", "UserId", "EMail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
